"""empty message

Revision ID: 5ac89d13904f
Revises: 80c4140ef3fe
Create Date: 2022-09-14 23:15:48.182540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac89d13904f'
down_revision = '80c4140ef3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'personajes', ['personajes'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personajes', type_='unique')
    # ### end Alembic commands ###
