"""empty message

Revision ID: 80c4140ef3fe
Revises: 8b348cb5fa6c
Create Date: 2022-09-14 23:12:28.064972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c4140ef3fe'
down_revision = '8b348cb5fa6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capitulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capitulos', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personajes', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personajes')
    op.drop_table('capitulos')
    # ### end Alembic commands ###
